// examples/angular/src/app/(modules)/device-dashboard/device-dashboard.page.ts
// Angular Page: Section container + layout. No data fetching.
// Purely arranges Sections on the screen.

import { Component } from '@angular/core';
import { BaseBox } from '@/app/theme/components/base-box';
import { DashboardOverviewSection } from './sections/dashboard-overview/dashboard-overview.section';

@Component({
  selector: 'app-device-dashboard-page',
  standalone: true,
  imports: [BaseBox, DashboardOverviewSection],
  templateUrl: './device-dashboard.page.html',
})
export class DeviceDashboardPage {}

// examples/react-vite/src/(modules)/device-dashboard/device-dashboard.page.tsx
// Page: Section container + layout. The module entry point.
// In CSR (React Vite): no API calls, no business logic.
// Purely arranges Sections on the screen.

import { BaseBox } from '@/theme/components/base-box';
import { DashboardOverview } from './sections/dashboard-overview/dashboard-overview.section';

export function DeviceDashboardPage() {
  return (
    <BaseBox>
      <h1>Device Dashboard</h1>
      <DashboardOverview />
    </BaseBox>
  );
}
