// examples/angular/src/app/(modules)/product-detail/sections/product-showcase/areas/product-gallery/components/thumbnail-selector/thumbnail-selector.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import type { ProductImage } from '../../../../../../models/product.models';

@Component({
  selector: 'app-thumbnail-selector',
  standalone: true,
  templateUrl: './thumbnail-selector.component.html',
  styleUrls: ['./thumbnail-selector.component.scss'],
})
export class ThumbnailSelectorComponent {
  @Input() image!: ProductImage;
  @Input() index = 0;
  @Input() isSelected = false;
  @Output() onSelect = new EventEmitter<number>();
}

<button
  class="thumbnail-btn"
  [class.thumbnail-btn-selected]="isSelected"
  (click)="onSelect.emit(index)"
>
  <img [src]="image.thumbnail" [alt]="image.alt" />
</button>

// examples/react-vite/src/(modules)/product-detail/sections/product-showcase/areas/product-gallery/components/thumbnail-selector/thumbnail-selector.component.tsx
// Delegate Component: Injected into ProductGalleryArea. Receives data as PROPS.
// Allowed because delegates are the exception to the "no props" rule.

import { BaseBox } from '@/theme/components/base-box/base-box';
import type { ProductImage } from '../../../../../../models/product.models';
import './thumbnail-selector.component.scss';

interface ThumbnailSelectorProps {
  image: ProductImage;
  index: number;
  isSelected: boolean;
  onSelect: () => void;
}

export function ThumbnailSelector({ image, isSelected, onSelect }: ThumbnailSelectorProps) {
  const borderClass = isSelected ? 'thumbnail-selected' : 'thumbnail-default';

  return (
    <BaseBox
      component="button"
      onClick={onSelect}
      className={`thumbnail ${borderClass}`}
    >
      <img
        src={image.thumbnail}
        alt={image.alt}
        className="thumbnail-image"
      />
    </BaseBox>
  );
}
