// examples/react-vite/src/App.tsx
// FFD React Vite Example — App Root
// In a real app, this would contain routing, global providers, and layout.
// For this example, we render the DeviceDashboard module directly.

import { DeviceDashboardPage } from './(modules)/device-dashboard/device-dashboard.page';
import { HeaderPage } from './(shared)/header/header';

export function App() {
  return (
    <>
      <HeaderPage activeSection="dashboard" />
      <main>
        <DeviceDashboardPage />
      </main>
    </>
  );
}

// examples/angular/src/app/app.component.ts
// App Root — renders the DeviceDashboardPage module.

import { Component } from '@angular/core';
import { DeviceDashboardPage } from './(modules)/device-dashboard/device-dashboard.page';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [DeviceDashboardPage],
  template: `
    <h1>FFD Angular Example</h1>
    <app-device-dashboard-page />
  `,
})
export class AppComponent {}

<app-header-page [cartCount]="0" />
<app-product-detail-page />
