// examples/react-vite/src/(modules)/device-dashboard/sections/dashboard-overview/areas/device-table/device-table.area.tsx
// Area: Business logic. CAN call its own specific APIs (e.g., POST).

import { useContext } from 'react';
import { BaseBox } from '@/theme/components/base-box';
import { updateDeviceStatus } from '@/services/devices/devices.api';
import { DashboardOverviewContext } from '../../../../state-management/dashboard-overview/dashboard-overview.reducer';
import { DeviceTableActions } from './delegate-components/device-table-actions.delegate';

export function DeviceTableArea() {
  const { state, setError, setDevices } = useContext(DashboardOverviewContext);

  if (state.devices.length === 0) return <BaseBox>No devices.</BaseBox>;

  return (
    <BaseBox>
      <h3>Devices</h3>
      {state.devices.map((d) => (
        <p key={d.id}>
          {d.name} — {d.status}{' '}
          <DeviceTableActions device={d} onToggle={(id) => {
            updateDeviceStatus(id, 'toggled')
              .then(() => setDevices(state.devices.map((dev) => dev.id === id ? { ...dev, status: 'offline' as const } : dev)))
              .catch((err) => setError(err.message));
          }} />
        </p>
      ))}
    </BaseBox>
  );
}

// examples/angular/src/app/(modules)/device-dashboard/sections/dashboard-overview/areas/device-table/device-table.area.ts
// Area: Business logic. CAN call its own specific APIs.

import { Component, inject } from '@angular/core';
import { DashboardOverviewService } from '../../../../state-management/dashboard-overview/dashboard-overview.service';
import { DevicesApiService } from '@/app/services/devices/devices.api';
import { DeviceTableActions } from './delegate-components/device-table-actions.delegate';

@Component({
  selector: 'app-device-table-area',
  standalone: true,
  imports: [DeviceTableActions],
  template: `
    <h3>Devices</h3>
    @if (service.devices().length === 0) {
      <p>No devices.</p>
    } @else {
      @for (d of service.devices(); track d.id) {
        <p>
          {{ d.name }} — {{ d.status }}
          <app-device-table-actions
            [device]="d"
            (toggle)="onToggle($event)"
          />
        </p>
      }
    }
  `,
})
export class DeviceTableArea {
  service = inject(DashboardOverviewService);
  private devicesApi = inject(DevicesApiService);

  onToggle(id: string): void {
    this.devicesApi
      .updateDeviceStatus(id, 'toggled')
      .then(() => {
        const devices = this.service.devices().map((dev) =>
          dev.id === id ? { ...dev, status: 'offline' as const } : dev,
        );
        this.service.setDevices(devices);
      })
      .catch((err) => this.service.setError(err.message));
  }
}
