// examples/angular/src/app/(modules)/device-dashboard/sections/dashboard-overview/dashboard-overview.section.ts
// Angular Section: Area container + data fetching. "The orchestrator."
// Provides the state service at this level so Areas can inject it.

import { Component, OnInit } from '@angular/core';
import { DashboardOverviewService } from '../../state-management/dashboard-overview/dashboard-overview.service';
import { DevicesApiService } from '@/app/services/devices/devices.api';
import { DeviceStatsArea } from './areas/device-stats/device-stats.area';
import { DeviceTableArea } from './areas/device-table/device-table.area';

@Component({
  selector: 'app-dashboard-overview',
  standalone: true,
  imports: [DeviceStatsArea, DeviceTableArea],
  providers: [DashboardOverviewService],
  template: `
    @if (service.loading()) {
      Loading...
    } @else if (service.error()) {
      Error: {{ service.error() }}
    } @else {
      <app-device-stats-area />
      <app-device-table-area />
    }
  `,
})
export class DashboardOverviewSection implements OnInit {
  constructor(
    public service: DashboardOverviewService,
    private devicesApi: DevicesApiService,
  ) {}

  ngOnInit(): void {
    this.devicesApi
      .fetchDevices()
      .then((res) => {
        const devices = res.devices.map((d) => ({
          id: d.id,
          name: d.name,
          status: d.status,
        }));
        this.service.setDevices(devices);
        this.service.setStats({
          total: devices.length,
          online: devices.filter((d) => d.status === 'online').length,
        });
      })
      .catch((err) => this.service.setError(err.message))
      .finally(() => this.service.setLoading(false));
  }
}

// examples/nextjs-app-router/src/app/(modules)/device-dashboard/sections/dashboard-overview/dashboard-overview.section.tsx
'use client';

// Section: Area container + data fetching. "The orchestrator."
// If Page passed initialData (SSR), skips fetch. Otherwise fetches on mount.

import { useContext, useEffect } from 'react';
import { BaseBox } from '@/app/theme/components/base-box';
import { fetchDevices } from '@/app/services/devices/devices.api';
import { DashboardOverviewContext } from '../../state-management/dashboard-overview/dashboard-overview.reducer';
import { DeviceStatsArea } from './areas/device-stats/device-stats.area';
import { DeviceTableArea } from './areas/device-table/device-table.area';

export function DashboardOverview() {
  const { state, setDevices, setStats, setLoading, setError } = useContext(DashboardOverviewContext);

  useEffect(() => {
    if (!state.loading || state.devices.length > 0) return; // SSR data present
    setLoading(true);
    fetchDevices()
      .then((res) => {
        const devices = res.devices.map((d) => ({ id: d.id, name: d.name, status: d.status }));
        setDevices(devices);
        setStats({ total: devices.length, online: devices.filter((d) => d.status === 'online').length });
      })
      .catch((err) => setError(err.message))
      .finally(() => setLoading(false));
  }, []);

  if (state.loading) return <BaseBox>Loading...</BaseBox>;
  if (state.error) return <BaseBox>Error: {state.error}</BaseBox>;

  return (
    <BaseBox>
      <DeviceStatsArea />
      <DeviceTableArea />
    </BaseBox>
  );
}
