// examples/angular/src/app/(modules)/product-detail/sections/related-products/related-products.section.ts
import { Component, OnInit, inject } from '@angular/core';
import { RelatedProductsStateManagement } from '../../state-management/related-products/related-products.state-management';
import { ProductsApiService } from '@/app/services/products/products.api';
import { mapRelatedProductsDTOToDomain } from '../../helpers/product-mapper.helper';
import { RelatedItemsArea } from './areas/related-items/related-items.area';

@Component({
  selector: 'app-related-products-section',
  standalone: true,
  imports: [RelatedItemsArea],
  providers: [RelatedProductsStateManagement],
  templateUrl: './related-products.section.html',
  styleUrls: ['./related-products.section.scss'],
})
export class RelatedProductsSection implements OnInit {
  state = inject(RelatedProductsStateManagement);
  private api = inject(ProductsApiService);

  ngOnInit(): void {
    this.api
      .fetchProduct('B0BSH3KTY6')
      .then((res) => {
        const products = mapRelatedProductsDTOToDomain(res);
        this.state.hydrate(products);
      })
      .catch((err) => this.state.error.set(err.message));
  }
}

// examples/react-vite/src/(modules)/product-detail/sections/related-products/related-products.section.tsx
// Section: Related products. "The orchestrator."
// State is provided by RelatedProductsProvider (wired in the Page).
// Separate business domain → separate Section with own state.

import { useContext, useEffect } from 'react';
import { BaseBox } from '@/theme/components/base-box/base-box';
import { fetchProduct } from '@/services/products/products.api';
import { RelatedProductsContext } from '../../state-management/related-products/related-products.reducer';
import { RelatedItemsArea } from './areas/related-items/related-items.area';
import { mapRelatedProductsDTOToDomain } from '../../helpers/product-mapper.helper';
import './related-products.section.scss';

export function RelatedProductsSection() {
  const { state, setRelatedProducts, setError } = useContext(RelatedProductsContext);

  useEffect(() => {
    loadRelatedProducts();
  }, []);

  const loadRelatedProducts = () =>
    fetchProduct('B0BSH3KTY6')
      .then(res => {
        setRelatedProducts(mapRelatedProductsDTOToDomain(res));
      })
      .catch(err => setError(err.message));

  if (state.relatedProducts.length === 0) return null;

  return (
    <BaseBox className="related-products">
      <BaseBox
        component="h2"
        className="related-products-heading"
      >
        Products related to this item
        <BaseBox
          component="span"
          className="related-products-sponsored-label"
        >
          Sponsored
        </BaseBox>
      </BaseBox>
      <RelatedItemsArea />
    </BaseBox>
  );
}
