// examples/angular/src/app/(modules)/device-dashboard/sections/dashboard-overview/areas/device-stats/device-stats.area.ts
// Area: Business logic for device statistics.
// Injects the Section's state service — NO @Input() from parent.

import { Component, inject } from '@angular/core';
import { AsyncPipe } from '@angular/common';
import { DashboardOverviewService } from '../../../state-management/dashboard-overview/dashboard-overview.service';

@Component({
  selector: 'app-device-stats-area',
  standalone: true,
  imports: [AsyncPipe],
  template: `
    <ng-container *ngIf="service.stats$ | async as stats">
      <h3>Device Overview</h3>
      <p>Total: {{ stats.total }}</p>
      <p>Online: {{ stats.online }}</p>
      <p>Offline: {{ stats.offline }}</p>
      <p>Warnings: {{ stats.warnings }}</p>
      <p>Avg Battery: {{ stats.averageBattery.toFixed(1) }}%</p>
    </ng-container>
  `,
})
export class DeviceStatsArea {
  service = inject(DashboardOverviewService);
}

// examples/nextjs-app-router/src/app/(modules)/device-dashboard/sections/dashboard-overview/areas/device-stats/device-stats.area.tsx
'use client';

// Area: Business logic for device statistics.
// Subscribes to Section context — NO props from parent.

import { BaseBox } from '@/app/theme/components/base-box';
import { useDashboardOverview } from '../../../state-management/dashboard-overview/dashboard-overview.reducer';

export function DeviceStatsArea() {
  const { state } = useDashboardOverview();
  if (!state.stats) return null;

  return (
    <BaseBox>
      <h3>Device Overview</h3>
      <p>Total: {state.stats.total}</p>
      <p>Online: {state.stats.online}</p>
      <p>Offline: {state.stats.offline}</p>
      <p>Warnings: {state.stats.warnings}</p>
      <p>Avg Battery: {state.stats.averageBattery.toFixed(1)}%</p>
    </BaseBox>
  );
}
