// examples/angular/src/app/(modules)/product-detail/sections/related-products/areas/related-items/related-items.area.ts
import { Component, inject } from '@angular/core';
import { RelatedProductsStateManagement } from '../../../../state-management/related-products/related-products.state-management';
import { ProductCardComponent } from './components/product-card/product-card.component';

@Component({
  selector: 'app-related-items-area',
  standalone: true,
  imports: [ProductCardComponent],
  templateUrl: './related-items.area.html',
  styleUrls: ['./related-items.area.scss'],
})
export class RelatedItemsArea {
  state = inject(RelatedProductsStateManagement);
}

// examples/react-vite/src/(modules)/product-detail/sections/related-products/areas/related-items/related-items.area.tsx
// Area: Business logic for related products display.
// Subscribes to Section context — NO props from parent.

import { useContext } from 'react';
import { BaseBox } from '@/theme/components/base-box/base-box';
import { RelatedProductsContext } from '../../../../state-management/related-products/related-products.reducer';
import { ProductCard } from './components/product-card/product-card.component';
import './related-items.area.scss';

export function RelatedItemsArea() {
  const { state } = useContext(RelatedProductsContext);

  return (
    <BaseBox className="related-items">
      {state.relatedProducts.map(product => (
        <ProductCard
          key={product.id}
          product={product}
        />
      ))}
    </BaseBox>
  );
}
