// examples/nextjs-app-router/src/app/(shared)/header/header.tsx
// Shared Feature: Header — follows Page→Section→Area structure.
// Receives configuration via props at the Page boundary.
// Receives global data via global context (current user, etc.).

import { BaseBox } from '@/theme/components/base-box/base-box';

export interface HeaderPageProps {
  activeSection?: string;
  showSearch?: boolean;
}

export function HeaderPage({
  activeSection = 'home',
  showSearch = true,
}: HeaderPageProps) {
  return (
    <BaseBox component="header">
      <nav>FFD Next.js Example — {activeSection}</nav>
    </BaseBox>
  );
}

// examples/angular/src/app/(shared)/header/header.ts
// Shared Feature: Header — follows Page→Section→Area structure.
// Receives configuration via @Input() at the Page boundary.

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-header-page',
  standalone: true,
  template: `
    <header>
      <nav>FFD Angular Example — {{ activeSection }}</nav>
    </header>
  `,
})
export class HeaderPage {
  @Input() activeSection = 'home';
  @Input() showSearch = true;
}
