// examples/angular/src/app/(modules)/product-detail/sections/related-products/areas/related-items/components/product-card/product-card.component.ts
import { Component, Input } from '@angular/core';
import type { RelatedProduct } from '../../../../../../models/product.models';

@Component({
  selector: 'app-product-card',
  standalone: true,
  templateUrl: './product-card.component.html',
  styleUrls: ['./product-card.component.scss'],
})
export class ProductCardComponent {
  @Input() product!: RelatedProduct;

  getStars(score: number): string {
    return '★'.repeat(Math.round(score));
  }
}

<div class="product-card">
  <img [src]="product.imageUrl" [alt]="product.title" class="product-card-image" />
  <a href="#" class="product-card-title">{{ product.title }}</a>
  <div class="product-card-rating">
    <span class="product-card-stars">{{ getStars(product.rating.score) }}</span>
    <span class="product-card-rating-count">{{ product.rating.count }}</span>
  </div>
  <div class="product-card-price">{{ product.currency }} {{ product.price.toFixed(2) }}</div>
  <div class="product-card-delivery">{{ product.delivery }}</div>
  @if (product.sponsored) {
    <span class="product-card-sponsored">Sponsored</span>
  }
</div>

// examples/react-vite/src/(modules)/product-detail/sections/related-products/areas/related-items/components/product-card/product-card.component.tsx
// Delegate Component: Product card in the related items grid.
// Receives product data as PROPS — delegates are the exception to the rule.

import { BaseBox } from '@/theme/components/base-box/base-box';
import { BaseCard } from '@/theme/components/base-card/base-card';
import type { RelatedProduct } from '../../../../../../models/product.models';
import './product-card.component.scss';

interface ProductCardProps {
  product: RelatedProduct;
}

export function ProductCard({ product }: ProductCardProps) {
  return (
    <BaseCard className="product-card">
      <BaseBox className="product-card-image">
        <img
          src={product.imageUrl}
          alt={product.title}
        />
      </BaseBox>
      <BaseBox className="product-card-title">{product.title}</BaseBox>

      <BaseBox className="product-card-rating">
        <BaseBox className="product-card-rating-stars">{'★'.repeat(Math.round(product.rating.score))}</BaseBox>
        <BaseBox className="product-card-rating-count">{product.rating.count}</BaseBox>
      </BaseBox>

      <BaseBox className="product-card-price">
        {product.currency} {product.price.toFixed(2)}
      </BaseBox>

      <BaseBox className="product-card-delivery">{product.delivery}</BaseBox>
      {product.sponsored && <BaseBox className="product-card-sponsored">Sponsored</BaseBox>}
    </BaseCard>
  );
}
