// examples/angular/src/app/(modules)/device-dashboard/sections/dashboard-overview/areas/device-chart/device-chart.area.ts
// Area: Business logic for device distribution chart.

import { Component, inject } from '@angular/core';
import { AsyncPipe } from '@angular/common';
import { DashboardOverviewService } from '../../../state-management/dashboard-overview/dashboard-overview.service';

@Component({
  selector: 'app-device-chart-area',
  standalone: true,
  imports: [AsyncPipe],
  template: `
    <ng-container *ngIf="service.stats$ | async as stats">
      <h3>Device Distribution</h3>
      <p>Online: {{ (stats.online / (stats.total || 1) * 100).toFixed(0) }}%</p>
      <p>Offline: {{ (stats.offline / (stats.total || 1) * 100).toFixed(0) }}%</p>
      <p>Warning: {{ (stats.warnings / (stats.total || 1) * 100).toFixed(0) }}%</p>
    </ng-container>
  `,
})
export class DeviceChartArea {}

// examples/react-vite/src/(modules)/device-dashboard/sections/dashboard-overview/areas/device-chart/device-chart.area.tsx
// Area: Business logic for the device distribution chart.
// Subscribes to Section context for shared stats data.

import { BaseBox } from '@/theme/components/base-box';
import { useDashboardOverview } from '../../../state-management/dashboard-overview/dashboard-overview.reducer';

export function DeviceChartArea() {
  const { state } = useDashboardOverview();

  if (!state.stats) return null;

  const total = state.stats.total || 1; // avoid div by zero

  return (
    <BaseBox>
      <BaseBox component="h3">Device Distribution</BaseBox>
      <BaseBox component="p">Online: {((state.stats.online / total) * 100).toFixed(0)}%</BaseBox>
      <BaseBox component="p">Offline: {((state.stats.offline / total) * 100).toFixed(0)}%</BaseBox>
      <BaseBox component="p">Warning: {((state.stats.warnings / total) * 100).toFixed(0)}%</BaseBox>
    </BaseBox>
  );
}
