// examples/angular/src/app/(modules)/device-dashboard/sections/dashboard-overview/areas/device-table/delegate-components/device-table-actions.delegate.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { BaseButton } from '@/app/theme/components/base-button';
import { Device } from '@/app/(modules)/device-dashboard/state-management/dashboard-overview/dashboard-overview.models';

@Component({
  selector: 'app-device-table-actions',
  standalone: true,
  imports: [BaseButton],
  templateUrl: './device-table-actions.delegate.html',
})
export class DeviceTableActions {
  @Input() device!: Device;
  @Output() toggle = new EventEmitter<string>();
}

// examples/react-vite/src/(modules)/device-dashboard/sections/dashboard-overview/areas/device-table/delegate-components/device-table-actions.delegate.tsx
import { BaseButton } from '@/theme/components/base-button';
import type { Device } from '@/(modules)/device-dashboard/models/device-models';

interface DeviceTableActionsProps {
  device: Device;
  onToggle: (id: string) => void;
}

export function DeviceTableActions({ device, onToggle }: DeviceTableActionsProps) {
  return <BaseButton onClick={() => onToggle(device.id)}>Toggle</BaseButton>;
}
