// examples/nextjs-app-router/src/app/(modules)/device-dashboard/sections/dashboard-overview/areas/device-table/delegate-components/device-table-actions.delegate.tsx
'use client';

// Delegate Component: Injectable action button for device table rows.
// Receives row data as PROPS from the table host — delegates allow props.

import { Device } from '../../../../../models/device.models';
import { BaseButton } from '@/app/theme/components/base-button';

export interface DeviceTableActionsProps {
  device: Device;
  onStatusChange: (id: string, status: Device['status']) => void;
}

export function DeviceTableActions({ device, onStatusChange }: DeviceTableActionsProps) {
  return (
    <BaseButton
      onClick={() =>
        onStatusChange(device.id, device.status === 'online' ? 'offline' : 'online')
      }
    >
      {device.status === 'online' ? 'Set Offline' : 'Set Online'}
    </BaseButton>
  );
}

// examples/angular/src/app/(modules)/device-dashboard/sections/dashboard-overview/areas/device-table/delegate-components/device-table-actions.delegate.ts
// Delegate Component: Injectable action button for device table rows.
// Receives data via @Input() — delegates are allowed to receive props.

import { Component, EventEmitter, Input, Output } from '@angular/core';

@Component({
  selector: 'app-device-table-actions',
  standalone: true,
  template: `
    <button (click)="onToggle()">
      {{ status === 'online' ? 'Set Offline' : 'Set Online' }}
    </button>
  `,
})
export class DeviceTableActions {
  @Input() status!: string;
  @Input() deviceId!: string;
  @Output() statusChange = new EventEmitter<{ id: string; status: string }>();

  onToggle(): void {
    const newStatus = this.status === 'online' ? 'offline' : 'online';
    this.statusChange.emit({ id: this.deviceId, status: newStatus });
  }
}
